In [1]:
# importing the packages
import pandas as pd
import numpy as np


In [2]:
from sklearn.datasets import load_iris


In [3]:
data = load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
data_x=pd.DataFrame(data=data.data,columns=data.feature_names)
data_x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [5]:
data_x.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
data_x.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [7]:
data_x.corr()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000

In [8]:
data_x.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [9]:
data_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [10]:
data_x.isnull()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                False             False              False             False
1                False             False              False             False
2                False             False              False             False
3                False             False              False             False
4                False             False              False             False
..                 ...               ...                ...               ...
145              False             False              False             False
146              False             False              False             False
147              False             False              False             False
148              False             False              False             False
149              False             False              False             False

[150 rows x 4 columns]

In [11]:
data_x.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [12]:
# rename the columns name
data_x.rename(columns={
    "sepal length (cm)":"sepal_length",
    "sepal width (cm)":"sepal_width",
    "petal length (cm)":"petal_length",
    "petal width (cm)":"petal_width"
},inplace=True)

In [13]:
data_x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [14]:
data_x.shape

(150, 4)

In [15]:
data_y=pd.DataFrame(data=data.target,columns=["class"])
data_y

class
0        0
1        0
2        0
3        0
4        0
..     ...
145      2
146      2
147      2
148      2
149      2

[150 rows x 1 columns]

In [16]:
data_y.head()

class
0      0
1      0
2      0
3      0
4      0

In [17]:
data_y.tail()

class
145      2
146      2
147      2
148      2
149      2

In [18]:
data_y.shape

(150, 1)

In [19]:
#Training and testing
from sklearn.model_selection import train_test_split
xtrain, xtest,ytrain,ytest = train_test_split(data_x,data_y,test_size=(0.2))


In [20]:
xtrain.shape, xtest.shape

((120, 4), (30, 4))

In [21]:
ytrain.shape,ytest.shape

((120, 1), (30, 1))

In [22]:
#prepare model
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()

In [23]:
LR.fit(xtrain,ytrain)

/home/speedtech/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [24]:
LR.coef_

array([[-0.39733267,  0.93426058, -2.36253277, -1.005328  ],
       [ 0.4324881 , -0.3202384 , -0.09225719, -0.85520657],
       [-0.03515542, -0.61402218,  2.45478995,  1.86053457]])

In [25]:
pred= LR.predict(xtest)

In [26]:
pred

array([1, 1, 2, 1, 2, 0, 2, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2, 1, 2, 0, 1, 0,
       2, 2, 1, 1, 0, 2, 2, 2])

In [27]:
pred=pd.DataFrame(pred)
pred


0
0   1
1   1
2   2
3   1
4   2
5   0
6   2
7   1
8   0
9   0
10  1
11  2
12  2
13  1
14  2
15  1
16  2
17  1
18  2
19  0
20  1
21  0
22  2
23  2
24  1
25  1
26  0
27  2
28  2
29  2

In [28]:
pred.head()

0
0  1
1  1
2  2
3  1
4  2

In [29]:
ytest.head()

class
54       1
65       1
105      2
84       1
107      2

In [30]:
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix
ac=accuracy_score(ytest,pred)
print("Accuracy score is:",ac*100)

Accuracy score is: 96.66666666666667


In [31]:
cr= classification_report(ytest,pred)
print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      0.92      0.96        12
           2       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [32]:
cm=confusion_matrix(ytest,pred)
print(cm)

[[ 6  0  0]
 [ 0 11  1]
 [ 0  0 12]]


In [33]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [34]:
lr.fit(xtrain,ytrain)

LinearRegression()

In [35]:
pred1=lr.predict(xtest)
pred1

array([[ 1.34188679],
       [ 1.19599212],
       [ 2.02699105],
       [ 1.38320778],
       [ 1.8114833 ],
       [-0.03134946],
       [ 1.58604035],
       [ 1.39203576],
       [-0.18988248],
       [-0.02400879],
       [ 1.11423522],
       [ 1.85727035],
       [ 1.715944  ],
       [ 1.10282468],
       [ 1.81977617],
       [ 1.39938859],
       [ 1.75546078],
       [ 1.31984835],
       [ 2.03884283],
       [-0.07412093],
       [ 1.15447313],
       [-0.02068472],
       [ 1.51461091],
       [ 2.24251918],
       [ 1.23984239],
       [ 1.28414194],
       [-0.1805396 ],
       [ 1.75270883],
       [ 1.46045357],
       [ 1.92536751]])

In [36]:
pred1=pd.DataFrame(pred1)
pred1.head()

0
0  1.341887
1  1.195992
2  2.026991
3  1.383208
4  1.811483

In [37]:
ytest.head()

class
54       1
65       1
105      2
84       1
107      2

In [38]:
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix
ac=accuracy_score(ytest,pred)
print("Accuracy score is:",ac*100)

Accuracy score is: 96.66666666666667


In [39]:
cr= classification_report(ytest,pred)
print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      0.92      0.96        12
           2       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [40]:
cm=confusion_matrix(ytest,pred)
print(cm)

[[ 6  0  0]
 [ 0 11  1]
 [ 0  0 12]]
